/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pcbuilcalc;

import javax.swing.JOptionPane;

/**
 *
 * @author excee
 */
public class Calc extends javax.swing.JFrame {

    /**
     * Creates new form Calc
     */
    String namaPelanggan, 
            nomorPelanggan, 
            alamatPelanggan, 
            processor, 
            storage0, 
            storage1, 
            pilihProcessor, 
            pilihMotherboard, 
            pilihRam, 
            pilihGraphiccard, 
            pilihPsu, 
            pilihStorage0, 
            pilihStorage1;

    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupProcessor = new javax.swing.ButtonGroup();
        groupStorage0 = new javax.swing.ButtonGroup();
        groupStorage1 = new javax.swing.ButtonGroup();
        txtTools = new javax.swing.JLabel();
        rbIntel = new javax.swing.JRadioButton();
        rbAMD = new javax.swing.JRadioButton();
        txtProci = new javax.swing.JLabel();
        cmbProci = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cmbMobo = new javax.swing.JComboBox<>();
        txtram = new javax.swing.JLabel();
        cmbRam = new javax.swing.JComboBox<>();
        txtvga = new javax.swing.JLabel();
        cmbvga = new javax.swing.JComboBox<>();
        txtpsu = new javax.swing.JLabel();
        cmbpsu = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbhdd0 = new javax.swing.JRadioButton();
        rbssd0 = new javax.swing.JRadioButton();
        rbhdd1 = new javax.swing.JRadioButton();
        rbssd1 = new javax.swing.JRadioButton();
        cmbstor0 = new javax.swing.JComboBox<>();
        cmbstor1 = new javax.swing.JComboBox<>();
        txtpelanggan = new javax.swing.JLabel();
        txttelp = new javax.swing.JLabel();
        txtalamat = new javax.swing.JLabel();
        tfpelanggan = new javax.swing.JTextField();
        tftelp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        txtcase = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtbundle = new javax.swing.JLabel();
        chckkibot = new javax.swing.JCheckBox();
        chckmouse = new javax.swing.JCheckBox();
        chckspeaker = new javax.swing.JCheckBox();
        chckmonitor = new javax.swing.JCheckBox();
        chckkursi = new javax.swing.JCheckBox();
        chckmic = new javax.swing.JCheckBox();
        btnSetuju = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTools.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        txtTools.setText("PC Build Tools");

        groupProcessor.add(rbIntel);
        rbIntel.setText("Intel");

        groupProcessor.add(rbAMD);
        rbAMD.setText("AMD");

        txtProci.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtProci.setText("Processor's");

        cmbProci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Intel Core i3 1305U", "Intel Core i3 1315U", "Intel Core i5 1345U", "Intel Core i5 13500H", "Intel Core i5 13500HX", "Intel Core i5 13600HX", "Intel Core i7 13700HX", "Intel Core i7 13850HX" }));
        cmbProci.setToolTipText("");
        cmbProci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProciActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("Motherboard");

        cmbMobo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "MSI MAG B760 TOMAHAWK WIFI", "Gigabyte B760M AORUS ELITE AX", "TUF GAMING B760M-PLUS WIFI II", "Asus ROG MAXIMUS Z790 HERO", "Gigabyte Z790 AORUS ELITE AX", "MSI MEG Z790 GODLIKE MAX WIFI 7" }));

        txtram.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtram.setText("RAM");

        cmbRam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtvga.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtvga.setText("Graphic Card");

        cmbvga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtpsu.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtpsu.setText("PSU");

        cmbpsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("Storage 0");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("Storage 1");

        groupStorage0.add(rbhdd0);
        rbhdd0.setText("HDD");

        groupStorage0.add(rbssd0);
        rbssd0.setText("SSD");

        groupStorage1.add(rbhdd1);
        rbhdd1.setText("HDD");

        groupStorage1.add(rbssd1);
        rbssd1.setText("SSD");

        cmbstor0.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbstor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtpelanggan.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtpelanggan.setText("Nama Pelanggan");

        txttelp.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txttelp.setText("No. Telp");

        txtalamat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtalamat.setText("Alamat Pengirinman");

        tftelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftelpActionPerformed(evt);
            }
        });

        taAlamat.setColumns(20);
        taAlamat.setRows(5);
        jScrollPane1.setViewportView(taAlamat);

        txtcase.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtcase.setText("Case");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtbundle.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtbundle.setText("Bundle");

        chckkibot.setText("Keyboard");
        chckkibot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckkibotActionPerformed(evt);
            }
        });

        chckmouse.setText("Mouse + pad");

        chckspeaker.setText("Speaker");

        chckmonitor.setText("Monitor");

        chckkursi.setText("Gaming Chair");
        chckkursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckkursiActionPerformed(evt);
            }
        });

        chckmic.setText("Mic + Arm");
        chckmic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckmicActionPerformed(evt);
            }
        });

        btnSetuju.setText("Cek");
        btnSetuju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetujuActionPerformed(evt);
            }
        });

        jButton2.setText("Hapus");

        jButton3.setText("Keluar");

        jCheckBox1.setText("Dual Channel");

        jButton1.setText("Pesan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(txtTools)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtram)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1))
                            .addComponent(txtvga))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbRam, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbvga, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtpsu)
                                .addGap(126, 126, 126)
                                .addComponent(cmbpsu, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(57, 57, 57)
                                    .addComponent(cmbMobo, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txttelp)
                                            .addComponent(txtpelanggan))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tftelp)
                                            .addComponent(tfpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtalamat)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtProci)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbIntel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbAMD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbProci, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSetuju)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbhdd0)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbssd0))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbhdd1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbssd1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbstor1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbstor0, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtcase)
                                .addGap(47, 47, 47)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtbundle)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chckkibot)
                                    .addComponent(chckspeaker))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chckmouse)
                                    .addComponent(chckmonitor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chckmic)
                                    .addComponent(chckkursi))))
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTools)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txttelp))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpelanggan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tftelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtalamat)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbIntel)
                    .addComponent(cmbProci, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbAMD)
                    .addComponent(txtProci)
                    .addComponent(jLabel2)
                    .addComponent(rbhdd0)
                    .addComponent(rbssd0)
                    .addComponent(cmbstor0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbMobo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(rbhdd1)
                        .addComponent(rbssd1)
                        .addComponent(cmbstor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcase)
                    .addComponent(jCheckBox1)
                    .addComponent(txtram)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbundle)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtvga)
                                    .addComponent(cmbvga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpsu)
                                    .addComponent(cmbpsu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSetuju, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chckkibot)
                            .addComponent(chckmouse)
                            .addComponent(chckkursi))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chckspeaker)
                            .addComponent(chckmonitor)
                            .addComponent(chckmic))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chckkibotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckkibotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chckkibotActionPerformed

    private void cmbProciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProciActionPerformed

    private void tftelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftelpActionPerformed

    private void btnSetujuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetujuActionPerformed
        // TODO add your handling code here:
        namaPelanggan = tfpelanggan.getText();
        nomorPelanggan = tftelp.getText();
        alamatPelanggan = taAlamat.getText();

        //        processor
        pilihProcessor = cmbProci.getSelectedItem().toString();

        if (rbIntel.isSelected()) {
            processor = "Intel";
        } else {
            processor = "AMD";
        }

        //        motherboard
        pilihMotherboard = cmbMobo.getSelectedItem().toString();

        //        Ram
        pilihRam = cmbRam.getSelectedItem().toString();

        //        graphiccard
        pilihGraphiccard = cmbvga.getSelectedItem().toString();

        //        psu
        pilihPsu = cmbpsu.getSelectedItem().toString();

        //        Storage0
        if (rbhdd0.isSelected()) {
            storage0 = "HDD";
        } else {
            storage0 = "SSD";
        }

        pilihStorage0 = cmbstor0.getSelectedItem().toString();

        //        Storage0
        if (rbhdd1.isSelected()) {
            storage1 = "HDD";
        } else {
            storage1 = "SSD";
        }

        pilihStorage1 = cmbstor1.getSelectedItem().toString();
    }//GEN-LAST:event_btnSetujuActionPerformed

    private void chckkursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckkursiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chckkursiActionPerformed

    private void chckmicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckmicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chckmicActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        namaPelanggan = JOptionPane.showInputDialog(this, "Masukkan nama kamu ");
        nomorPelanggan = JOptionPane.showInputDialog(this, "Masukkan nomor telephone ");

        JOptionPane.showMessageDialog(this, "Hallo Aku " + namaPelanggan);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSetuju;
    private javax.swing.JCheckBox chckkibot;
    private javax.swing.JCheckBox chckkursi;
    private javax.swing.JCheckBox chckmic;
    private javax.swing.JCheckBox chckmonitor;
    private javax.swing.JCheckBox chckmouse;
    private javax.swing.JCheckBox chckspeaker;
    private javax.swing.JComboBox<String> cmbMobo;
    private javax.swing.JComboBox<String> cmbProci;
    private javax.swing.JComboBox<String> cmbRam;
    private javax.swing.JComboBox<String> cmbpsu;
    private javax.swing.JComboBox<String> cmbstor0;
    private javax.swing.JComboBox<String> cmbstor1;
    private javax.swing.JComboBox<String> cmbvga;
    private javax.swing.ButtonGroup groupProcessor;
    private javax.swing.ButtonGroup groupStorage0;
    private javax.swing.ButtonGroup groupStorage1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbAMD;
    private javax.swing.JRadioButton rbIntel;
    private javax.swing.JRadioButton rbhdd0;
    private javax.swing.JRadioButton rbhdd1;
    private javax.swing.JRadioButton rbssd0;
    private javax.swing.JRadioButton rbssd1;
    private javax.swing.JTextArea taAlamat;
    private javax.swing.JTextField tfpelanggan;
    private javax.swing.JTextField tftelp;
    private javax.swing.JLabel txtProci;
    private javax.swing.JLabel txtTools;
    private javax.swing.JLabel txtalamat;
    private javax.swing.JLabel txtbundle;
    private javax.swing.JLabel txtcase;
    private javax.swing.JLabel txtpelanggan;
    private javax.swing.JLabel txtpsu;
    private javax.swing.JLabel txtram;
    private javax.swing.JLabel txttelp;
    private javax.swing.JLabel txtvga;
    // End of variables declaration//GEN-END:variables
}
