/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pcbuilcalc;

import javax.swing.JOptionPane;

/**
 *
 * @author excee
 */
public class Calc extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    String namaPelanggan, 
            nomorPelanggan, 
            alamatPelanggan, 
            processor, 
            storage0, 
            storage1, 
            pilihProcessor, 
            pilihMotherboard, 
            pilihRam, 
            pilihGraphiccard, 
            pilihPsu, 
            pilihStorage0, 
            pilihStorage1,
            pilihCase,
            channel,
            kibot,
            mouse,
            kursi,
            monitor,
            speaker,
            mic;

    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupProcessor = new javax.swing.ButtonGroup();
        groupStorage0 = new javax.swing.ButtonGroup();
        groupStorage1 = new javax.swing.ButtonGroup();
        txtTools = new javax.swing.JLabel();
        txtProci = new javax.swing.JLabel();
        cmbProci = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cmbMobo = new javax.swing.JComboBox<>();
        txtram = new javax.swing.JLabel();
        cmbRam = new javax.swing.JComboBox<>();
        txtvga = new javax.swing.JLabel();
        cmbvga = new javax.swing.JComboBox<>();
        txtpsu = new javax.swing.JLabel();
        cmbpsu = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbhdd0 = new javax.swing.JRadioButton();
        rbssd0 = new javax.swing.JRadioButton();
        rbhdd1 = new javax.swing.JRadioButton();
        rbssd1 = new javax.swing.JRadioButton();
        cmbstor0 = new javax.swing.JComboBox<>();
        cmbstor1 = new javax.swing.JComboBox<>();
        txtcase = new javax.swing.JLabel();
        jComboBoxCase = new javax.swing.JComboBox<>();
        txtbundle = new javax.swing.JLabel();
        chckkibot = new javax.swing.JCheckBox();
        chckmouse = new javax.swing.JCheckBox();
        chckspeaker = new javax.swing.JCheckBox();
        chckmonitor = new javax.swing.JCheckBox();
        chckkursi = new javax.swing.JCheckBox();
        chckmic = new javax.swing.JCheckBox();
        btnSetuju = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCheckBoxDual = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTools.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        txtTools.setText("PC Build Tools");

        txtProci.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtProci.setText("Processor's");

        cmbProci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Intel Core i3 1315U", "Intel core i3 1305U", "Intel Core i5 13600HX", "Intel Core i7 13850HX", "AMD Ryzen 9 7950X3D", "AMD Ryzen 7 7800X3D", "AMD Ryzen 5 7600X", "AMD Ryzen 5 7500X" }));
        cmbProci.setToolTipText("");
        cmbProci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProciActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("Motherboard");

        cmbMobo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "MSI MAG B760 TOMAHAWK WIFI intel", "Asus ROG MAXIMUS Z790 HERO intel", "Gigabyte Z790 AORUS ELITE AX intel", "MSI MEG Z790 GODLIKE MAX WIFI 7 intel", "MSI MEG X670E ACE AMD", "MSI MAG X670 TOMAHAWK WIFI AMD", "ASUS ROG Strix X670E-E Gaming WiFi AMD", "Gigabyte X670E AORUS MASTER AMD" }));

        txtram.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtram.setText("RAM");

        cmbRam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Corsair Dominator Platinum RGB DDR5 16gb", "G.Skill Trident Z5 RGB DDR5 32gb", "Kingston FURY Beast DDR5 8gb", "MSI Spatium DDR5 16gb", " ", " " }));

        txtvga.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtvga.setText("Graphic Card");

        cmbvga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "MSI RTX 3090 Ti Suprim X", "MSI RTX 3070 Gaming X Trio", "MSI RTX 3060 Ventus 2X OC", "MSI RTX 4090 SUPRIM X" }));

        txtpsu.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtpsu.setText("PSU");

        cmbpsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Corsair RMx Series 1200W 80+ Gold", "Corsair HX Series 1200W 80+ Platinum", "Cooler Master V Gold 1000W 80+ Gold", "Thermaltake Toughpower Grand RGB 1000W 80+ Gold" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("Storage 0");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("Storage 1");

        groupStorage0.add(rbhdd0);
        rbhdd0.setText("HDD");

        groupStorage0.add(rbssd0);
        rbssd0.setText("SSD");

        groupStorage1.add(rbhdd1);
        rbhdd1.setText("HDD");

        groupStorage1.add(rbssd1);
        rbssd1.setText("SSD");

        cmbstor0.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "128gb", "256gb", "512gb", "1tb", "2tb" }));

        cmbstor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "128gb", "256gb", "512gb", "1tb", "2tb" }));

        txtcase.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtcase.setText("Case");

        jComboBoxCase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "NZXT H510", "NZXT H510 Elite", "NZXT H510 Flow" }));

        txtbundle.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtbundle.setText("Bundle");

        chckkibot.setText("Keyboard");
        chckkibot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckkibotActionPerformed(evt);
            }
        });

        chckmouse.setText("Mouse + pad");

        chckspeaker.setText("Speaker");

        chckmonitor.setText("Monitor");

        chckkursi.setText("Gaming Chair");
        chckkursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckkursiActionPerformed(evt);
            }
        });

        chckmic.setText("Mic + Arm");
        chckmic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckmicActionPerformed(evt);
            }
        });

        btnSetuju.setText("Cek");
        btnSetuju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetujuActionPerformed(evt);
            }
        });

        jButton2.setText("Hapus");

        jButton3.setText("Keluar");

        jCheckBoxDual.setText("Dual Channel");

        jButton1.setText("Pesan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtHasil.setColumns(20);
        txtHasil.setRows(5);
        jScrollPane1.setViewportView(txtHasil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtram)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBoxDual))
                                    .addComponent(txtvga))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbRam, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbvga, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtpsu)
                                .addGap(126, 126, 126)
                                .addComponent(cmbpsu, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(57, 57, 57)
                                    .addComponent(cmbMobo, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtProci)
                                    .addGap(70, 70, 70)
                                    .addComponent(cmbProci, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSetuju)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbhdd0)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbssd0))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbhdd1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbssd1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbstor1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbstor0, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtcase)
                                .addGap(47, 47, 47)
                                .addComponent(jComboBoxCase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtbundle)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chckkibot)
                                    .addComponent(chckspeaker))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chckmouse)
                                    .addComponent(chckmonitor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chckmic)
                                    .addComponent(chckkursi)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(txtTools)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTools)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProci)
                            .addComponent(cmbProci, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbMobo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbRam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxDual)
                            .addComponent(txtram))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtvga)
                            .addComponent(cmbvga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpsu)
                            .addComponent(cmbpsu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rbhdd0)
                            .addComponent(rbssd0)
                            .addComponent(cmbstor0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rbhdd1)
                            .addComponent(rbssd1)
                            .addComponent(cmbstor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcase)
                            .addComponent(jComboBoxCase, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbundle)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chckkibot)
                                    .addComponent(chckmouse)
                                    .addComponent(chckkursi))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chckspeaker)
                                    .addComponent(chckmonitor)
                                    .addComponent(chckmic))))))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetuju, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chckkibotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckkibotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chckkibotActionPerformed

    private void cmbProciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProciActionPerformed

    private void btnSetujuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetujuActionPerformed
        // TODO add your handling code here:
        //        processor
        pilihProcessor = cmbProci.getSelectedItem().toString();

        //        motherboard
        pilihMotherboard = cmbMobo.getSelectedItem().toString();

        //        Ram
        if (jCheckBoxDual.isSelected()) {
            channel = "Dual Channel";
        } else {
            channel = "";
        }
        
        pilihRam = cmbRam.getSelectedItem().toString();

        //        graphiccard
        pilihGraphiccard = cmbvga.getSelectedItem().toString();

        //        psu
        pilihPsu = cmbpsu.getSelectedItem().toString();

        //        Storage0
        if (rbhdd0.isSelected()) {
            storage0 = "HDD";
        } else {
            storage0 = "SSD";
        }

        pilihStorage0 = cmbstor0.getSelectedItem().toString();

        //        Storage1
        if (rbhdd1.isSelected()) {
            storage1 = "HDD";
        } else {
            storage1 = "SSD";
        }

        pilihStorage1 = cmbstor1.getSelectedItem().toString();
        
//        case
        pilihCase = jComboBoxCase.getSelectedItem().toString();
        
//        Bundle
        if (chckkibot.isSelected()) {
            kibot = "Keyboard";
        } else {
            kibot = "";
        }
        if (chckmouse.isSelected()) {
            mouse = "Mouse + Pad";
        } else {
            mouse = "";
        }
        if (chckkursi.isSelected()) {
            kursi = "Gaming Chair";
        } else {
            kursi = "";
        }
        if (chckspeaker.isSelected()) {
            speaker = "Speaker";
        } else {
            speaker = "";
        }
        if (chckmonitor.isSelected()) {
            monitor = "Monitor";
        } else {
            monitor = "";
        }
        if (chckmic.isSelected()) {
            mic = "Mic + ARM";
        } else {
            mic = "";
        }

        
        txtHasil.setText("Processor\t: " + pilihProcessor +
                "\nMotherboard\t: " + pilihMotherboard + 
                "\nRam\t: " + channel + pilihRam +
                "\nGPU\t: " + pilihGraphiccard + 
                "\nPSU\t: " + pilihPsu + 
                "\nStorage0\t: " + storage0 + pilihStorage0 +
                "\nStorage\t: " + storage1 + pilihStorage1 +
                "\nCase\t: " + pilihCase + 
                "\nBundle\t: " + "\n" + kibot + "\n" + mouse + "\n" + kursi + "\n" + speaker + "\n" + monitor + "\n" + mic);
    }//GEN-LAST:event_btnSetujuActionPerformed

    private void chckkursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckkursiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chckkursiActionPerformed

    private void chckmicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckmicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chckmicActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        namaPelanggan = JOptionPane.showInputDialog(this, "Masukkan nama ");
        nomorPelanggan = JOptionPane.showInputDialog(this, "Masukkan nomor telephone ");
        alamatPelanggan = JOptionPane.showInputDialog(this, "Masukkan alamat  ");

        JOptionPane.showMessageDialog(this, "Nama       : " + namaPelanggan +
                "\nNo   : " + nomorPelanggan +
                "\nAlamat       : " + alamatPelanggan);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSetuju;
    private javax.swing.JCheckBox chckkibot;
    private javax.swing.JCheckBox chckkursi;
    private javax.swing.JCheckBox chckmic;
    private javax.swing.JCheckBox chckmonitor;
    private javax.swing.JCheckBox chckmouse;
    private javax.swing.JCheckBox chckspeaker;
    private javax.swing.JComboBox<String> cmbMobo;
    private javax.swing.JComboBox<String> cmbProci;
    private javax.swing.JComboBox<String> cmbRam;
    private javax.swing.JComboBox<String> cmbpsu;
    private javax.swing.JComboBox<String> cmbstor0;
    private javax.swing.JComboBox<String> cmbstor1;
    private javax.swing.JComboBox<String> cmbvga;
    private javax.swing.ButtonGroup groupProcessor;
    private javax.swing.ButtonGroup groupStorage0;
    private javax.swing.ButtonGroup groupStorage1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBoxDual;
    private javax.swing.JComboBox<String> jComboBoxCase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbhdd0;
    private javax.swing.JRadioButton rbhdd1;
    private javax.swing.JRadioButton rbssd0;
    private javax.swing.JRadioButton rbssd1;
    private javax.swing.JTextArea txtHasil;
    private javax.swing.JLabel txtProci;
    private javax.swing.JLabel txtTools;
    private javax.swing.JLabel txtbundle;
    private javax.swing.JLabel txtcase;
    private javax.swing.JLabel txtpsu;
    private javax.swing.JLabel txtram;
    private javax.swing.JLabel txtvga;
    // End of variables declaration//GEN-END:variables
}
